name: README Repos List
on:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Repo-List-Generator
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - name: Echo Output
        run: |
          echo repo: ${{steps.repo.outputs.repo}}
          echo repoList: ${{steps.repo.outputs.repoList}}
          echo repoList_ALL: ${{steps.repo.outputs.repoList_ALL}}
          echo repoList_PRIVATE: ${{steps.repo.outputs.repoList_PRIVATE}}
          echo repoList_FORK: ${{steps.repo.outputs.repoList_FORK}}
          echo privateList: ${{steps.repo.outputs.privateList}}
          echo forkList: ${{steps.repo.outputs.forkList}}
          echo emptyList: ${{steps.repo.outputs.emptyList}}
          echo archivedList: ${{steps.repo.outputs.emptyList}}

            
